lmsimpacta/urls.py
from django.conf.urls import url
from django.contrib import admin

from core.views import *

from django.contrib.auth.views import login, logout


urlpatterns = [

    url(r'^admin/',     admin.site.urls),
    url(r'^$',          index,                                     name="home" ),
    url(r'^matricula/', matricula,                                 name="matricula"),

    url(r'^entrar/',    login,   {"template_name":"login.html"},   name="login"),
    url(r'^sair/',      logout,  {"template_name":"index.html"},   name="logout"),



    url(r'^pagina_inicial_professor/', pagina_inicial_professor,   name="pagina_inicial_professor"),
        url(r'^perfil_professor/',         perfil_professor,           name="perfil_professor"),

    url(r'^subir_aula/',               subir_aula,                 name="subir_aula"),

    url(r'^boletim/',                  boletim,                    name="boletim"),
        url(r'^notas/',                    notas,                      name="notas"),

    url(r'^seleciona_turma_falta/',   seleciona_turma_falta,       name="seleciona_turma_falta"),    
        url(r'^faltas/',                   faltas,                     name="faltas"),

    url(r'^mensagens/',               mensagens,                   name="mensagens"), 


    url(r'^subir_atividades/',        subir_atividades,            name="subir_atividades"), 


]

core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager


#from django.contrib.auth.models import User
class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, ra, password, **extra_fields):
        if not ra:
            raise ValueError('RA precisa ser preenchido')
        user = self.model(ra=ra, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, ra, password=None, **extra_fields):
        return self._create_user(ra, password, **extra_fields)

    def create_superuser(self, ra, password, **extra_fields):
        return self._create_user(ra, password, **extra_fields)


class Usuario(AbstractBaseUser):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)
    ra = models.IntegerField(unique=True)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=150)
    perfil = models.CharField(max_length=1, default='C')
    ativo = models.BooleanField(default=True)

    USERNAME_FIELD = 'ra'
    REQUIRED_FIELDS = ['nome']

    objects = UsuarioManager()

    @property   #Objetos para roubar
    def is_staff(self):
        return self.perfil == 'C'  


    def has_perm(self, perm, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True


    def get_short_name(self):
        return self.nome
    def get_full_name(self):
        return self.nome

    def __str__(self):
        return self.nome


class Curso(models.Model):
    sigla = models.CharField(max_length=5)
    nome = models.CharField(unique=True, max_length=50)
    tipo = models.CharField(max_length=50, blank=True)
    carga_horaria = models.IntegerField(default=1000)
    ativo = models.BooleanField(default = True)
    descricao = models.TextField(blank=True)

    def __str__(self):
        return self.nome 

class Aluno(Usuario):
    celular = models.CharField(max_length=50)
    curso = models.ForeignKey(Curso)

class Professor(Usuario):
    apelido = models.CharField(max_length=30,unique = True, null = True)
    curso = models.ForeignKey(Curso)

class GradeCurricular(models.Model):
    curso = models.ForeignKey(to='Curso', db_column='curso', null=False) #onetomany
    ano = models.SmallIntegerField(null=False)
    semestre = models.CharField(max_length=1,null=False)

    USERNAME_FIELD = 'ano'


class Periodo(models.Model):
    curso = models.ForeignKey(to='GradeCurricular', db_column="curso", null=False, blank=False) #onetomany
    ano = models.ForeignKey(to='GradeCurricular', db_column="ano", null=False, related_name="ano_grade")
    semestre = models.ForeignKey(to='GradeCurricular', db_column="semestre", null=False,related_name="semestre_grade")
    numero = models.SmallIntegerField(null=False) #tinyint

    USERNAME_FIELD = 'numero'


class Disciplina(models.Model):
    nome = models.CharField(max_length=240,primary_key=True)
    carga_horaria = models.SmallIntegerField()  #tinyint
    teoria = models.DecimalField(max_digits=3,decimal_places=2)
    pratica = models.DecimalField(max_digits=3,decimal_places=2)
    ementa = models.TextField()
    competencias = models.TextField()
    habilidades = models.TextField()
    conteudo = models.TextField()
    bibliografia_complementar = models.TextField()
    bibliografia_basica = models.TextField()   



class Matricula(models.Model):
    nome = models.CharField(primary_key=True, max_length=50)
    sobrenome = models.CharField(max_length=50)
    endereco = models.CharField(max_length=50)
    numero = models.IntegerField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.nome
'''
class GradeCurricular(models.Model):
    curso = models.ForeignKey(to='Curso', related_name="gradesCurriculares", null=False, blank=False) #onetomany
    ano = models.SmallIntegerField(null=False)
    semestre = models.CharField(max_length=1,null=False)

    def __str__(self):
        return self.nome     

class Periodo(models.Model):
    GradeCurricular = models.ForeignKey(to='GradeCurricular', related_name="periodos", null=False, blank=False) #onetomany
    numero = models.SmallIntegerField(null=False) #tinyint
    disciplinas = models.ManyToManyField('Disciplina', db_table='PeriodoDisicplina', related_name='periodos', blank=False)

    def __str__(self):
        return self.nome  

'''










        



core/forms.py
from django import forms
from core.models import Curso
from django import forms
from django.contrib.auth.models import User

from core.models import Curso,Aluno, Matricula

class MatriculaForm(forms.ModelForm):
    class Meta:
        model = Matricula
        fields = "__all__"

core/views.py
from django.shortcuts import render
from core.models import *

from django.shortcuts import render, redirect
from django.views.generic.base import View
from core.forms import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.

# PARTE EXTERNA (MATRICULAR-SE E LOGIN)

def index(request):
    contexto = {
        'cursos': Curso.objects.all()
            
    } #Esse comando puxa as inf. do BD e printa na página
    return render(request,"index.html",contexto)


def matricula(request):
    form = None
    form = MatriculaForm(request.POST)
    if request.POST:
        form = MatriculaForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,"login.html")
    else:
        form = MatriculaForm()
    return render(request,"matricula.html")


def login(request):
    return render(request,"logn.html")




# DEPOIS DE LOGAR - PROFESSOR -
#def checa_professor(user):
#     return user.perfil == 'A'

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def pagina_inicial_professor(request):
    return render(request,"Professor/pagina_inicial.html")
def perfil_professor(request):
    return render(request, "Professor/PerfilProf.html")

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def subir_aula(request):
    return render(request,"Professor/subir_aula.html")

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def boletim(request):
    return render(request,"Professor/boletim.html")

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def notas(request):
    return render(request,"Professor/notas.html")

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def seleciona_turma_falta(request):
    return render(request,"Professor/seleciona_turma_falta.html")

#@user_passes_test(checa_professor, login_url='/?error=acesso', redirect_field_name=None)
#@login_required(login_url='/entrar')
def faltas(request):
    return render(request,"Professor/faltas.html")

def aplicar_teste(request):
    pass

def mensagens(request):
    return render(request,"Professor/mensagens.html")

def subir_atividades(request):
    return render(request,"Professor/subir_atividades.html")



    



core/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>LSM IMPACTA </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/css/materialize.css"/>
  </head>

  <body>
      <header>
        <h1>Faculdade </h1>
        <nav>
          <a href="/">Index</a>
          <a href="contato">Contato</a>

        </nav>
      </header>
      <main>
        {% block main %}

        {% endblock %}
      </main>  
  </body>

</html>

core/templates/base_externa.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title> {% block titulo %} {% endblock %} </title>    <!-- TITULO --><!-- TITULO --><!-- TITULO --><!-- TITULO --><!-- TITULO -->                                     

  <!-- CSS  -->
  <link    rel="stylesheet" href="{% static 'fonts\roboto\Roboto-Light.woff' %}" />

  <link  type="text/css" rel="stylesheet" media="screen,projection" href= "{% static 'css/materialize.css' %}" />

  <link  type="text/css" rel="stylesheet" media="screen,projection" href= "{% static 'css/style.css' %}"/>

</head>
<body class="grey darken-1">

  <nav class="grey darken-4" role="navigation">
    <div class="nav-wrapper container"><img src="{% static 'img/logo.png' %}" width="200px" />
      
      <ul class="right hide-on-med-and-down">
        <li><a class="blue-text text-lighten-3" href= "/matricula"> Matricula </a></li>
        <li><a class="blue-text text-lighten-3" href= "/"> HomePage </a></li>
          
        {% if not user.is_authenticated %}  
          <li><a class="blue-text text-lighten-3" href= "/entrar"> Login </a></li>
        {% else %}
          <li><a class="blue-text text-lighten-3" href= "/pagina_inicial_professor"> Área do Professor </a></li>  
        {% endif %}

          
          
          
          
          

      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href= ><h2> </h2></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

    {% block corpo %}


    {% endblock %}


  
  <footer class="page-footer black">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Impacta</h5>
          <p class="grey-text text-lighten-4">A Faculdade Impacta Tecnologia nasceu da percepção de um Grupo, que desde 1998 é referência em TI, Gestão e Design, para suprir a falta de mão de obra especializada do mercado de tecnologia e oferecer uma formação completa e multidisciplinar aos alunos. </p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Contato</h5>
          <ul>
            <li class="white-text">Comercial</br>11 3254-8300</li>
            <li class="white-text">Secretaria</br>11 5593-5345</li> 
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Endereço</h5>
          <ul>
            <li class="white-text">Unidade - Barra Funda Avenida Rudge, 315 - Barra Funda São Paulo / SP</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
          CNPJ: 59.069.914/0001-51
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  </body>
</html>




core/templates/index.html
{% extends 'base_externa.html' %}

{% load static %}

{% block titulo %} HOME PAGE {% endblock %} 

{% block corpo %}
<h1> HOMEEEE PAAGEEEE </h1>
<ul>
        {% for curso in cursos %}
            <li class="{{curso.classe}}"> {{curso.sigla}} - {{ curso.nome }}  </li>
           
        {% endfor %}    
</ul>
{% endblock %}

core/templates/login.html
{% extends 'base_externa.html' %}

{% load static %}

{% block titulo %} Login {% endblock %} 


<!-- Colocar Apenas Nome do URLS -->


{% block corpo %}
<form method="POST">
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center blue-text text-lighten-1">Login</h1>
      <div class="row center">
         
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn-large waves-effect waves-light blue" type="submit" >Entrar</button>           
              <br />
</form>
      </div>
      <br><br>

    </div>
  </div> 
{% endblock %}    

core/templates/matricula.html
{% extends 'base_externa.html' %}

{% load static %}

{% block titulo %} Matricula {% endblock %} 



{% block corpo %}

    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
        <br><br>
        <h1 class="header center blue-text text-lighten-1">Matricula</h1>
        <div class="row center">
                <div class="row">
                    <form method="post" action="{ url 'matricula'}" class="col s12">  
                            {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s6">
                                <input  id="id_nome" name="nome" type="text" class="validate" required>
                                <label for="id_nome">Primeiro Nome</label>
                            </div>
                            <div class="input-field col s6">
                                <input id="id_sobrenome" name="sobrenome" type="text" class="validate" required>
                                <label for="id_sobrenome">Sobrenome</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input  id="id_endereco" name="endereco" type="text" class="validate" required>
                                <label for="id_endereco">Endereço</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="id_numero" name="numero" type="text" class="validate" required>
                                <label for="id_numero">Número</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="id_email" name="email" type="email" class="validate" >
                                <label for="id_email">Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <select>
                                    <optgroup label="Graduação">
                                        <option value="1">Option1</option>
                                        <option value="2">Option 2</option>
                                    </optgroup>
                                    <optgroup label="Pós Graduação">
                                        <option value="3">Option 3</option>
                                        <option value="4">Option 4</option>
                                    </optgroup>
                                </select>
                                <label>Optgroups</label>
                            </div>
                        </div>
                        <div class="file-field input-field">
                                
                            <p>RG, CPF, Comprovante de Residência, Histórico Escolar, Foto 3x4</p>
                            <div class="btn">
                                <span>File</span>
                                <input type="file" id="id_file" name="file" multiple accept=".jpg, .pdf, .png, .txt">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload one or more files">
                            </div>
                        </div>
                        <br />

                        <button class="btn-large waves-effect waves-light blue" type="submit">Enviar</button><br /><br />
                    
                    </form>


                    {% if form.errors %}
                    <div class="red-text" style="font-size: 45px">
                        
                        <b><p>{{form.non_field_errors}} </p></b>
                        
                     </div> 
                     {% endif %}      
                     </div>
                    
                    </div>
                <br><br>

    </div>
    </div>
   
{% endblock %}    